language: ruby
rvm:
  - 2.1.10
  - 2.2.1
  - 2.2.2
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gem install bundler -v '~> 1.0'
env:
  - ACTIVE_MODEL_VERSION='~> 3.2.0'
  - ACTIVE_MODEL_VERSION='~> 4.0'
  - ACTIVE_MODEL_VERSION='~> 5.1'
  - ACTIVE_MODEL_VERSION='~> 5.2'
jobs:
  exclude:
    - rvm: 2.1.10
      env: ACTIVE_MODEL_VERSION='~> 5.1'
    - rvm: 2.1.10
      env: ACTIVE_MODEL_VERSION='~> 5.2'
    - rvm: 2.2.1
      env: ACTIVE_MODEL_VERSION='~> 5.1'
    - rvm: 2.2.1
      env: ACTIVE_MODEL_VERSION='~> 5.2'
    - rvm: 2.7.0
      env: ACTIVE_MODEL_VERSION='~> 3.2.0'
    - rvm: 2.7.0
      env: ACTIVE_MODEL_VERSION='~> 4.0'
    - rvm: 2.7.0
      env: ACTIVE_MODEL_VERSION='~> 5.1'
gemfile: Gemfile
notifications:
  recipients:
    - jeremy@tregunna.ca
